# Generated by Django 5.1.4 on 2024-12-07 11:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_task_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='attachment'),
        ),
    ]
